# See limits on Lambda@Edge http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-limits.html#limits-lambda-at-edge

service: ${env:SERVICE_NAME}

provider:
  name: aws
  region: ${env:REGION}
  role: LambdaEdgeRole
  runtime: nodejs10.x
  memorySize: ${env:MEMORY_SIZE}
  timeout: ${env:TIMEOUT}
  stage: ${ opt:stage }
  deploymentBucket: ${env:DEPLOYMENT_BUCKET}

functions:
  subdirIndex:
    handler: src/origin_request/subdir-index.handler
    name: ${self:service}-indexhtml-${opt:stage}

  headers:
    handler: src/origin_response/sec-headers.handler
    name: ${self:service}-headers-${opt:stage}

  queryRedirect:
    handler: src/viewer_request/qs-redirect.handler
    name: ${self:service}-queries-${opt:stage}

  basicAuth:
    handler: src/viewer_request/basic-auth.handler
    name: ${self:service}-auth-${opt:stage}
    package:
      include:
        - viewer_request/opts.json

  corsViewerResponse:
    handler: src/viewer_response/cors.handler
    name: ${self:service}-cors-${opt:stage}

resources:
  Resources:
    LambdaEdgeRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Statement:
          - Effect: Allow
            Principal:
              Service:
                - edgelambda.amazonaws.com
                - lambda.amazonaws.com
            Action:
            - sts:AssumeRole
        Policies:
          - PolicyName: LambdaEdgeExecutionRole
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: "arn:aws:logs:*:*:*"
