# See limits on Lambda@Edge http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-limits.html#limits-lambda-at-edge
service: edge-lambda

provider:
  name: aws
  region: us-east-1 # Edge lambdas must exist in us-east-1
  role: LambdaEdgeRole
  runtime: nodejs12.x
  memorySize: 128
  timeout: 5 # Timeouts for edge lambdas must not exceed 5s
  stage: ${ opt:stage }
  deploymentBucket: ${self:custom.deploymentBucket}
  versionFunctions: true

custom:
  deploymentBucket: ${ssm:/${opt:client}/${opt:stage}/DEPLOYMENT_BUCKET}

functions:
  subdirIndex:
    handler: src/origin_request/subdir-index.handler
    name: ${self:service}-indexhtml-${opt:stage}

  headers:
    handler: src/origin_response/sec-headers.handler
    name: ${self:service}-headers-${opt:stage}

  queryRedirect:
    handler: src/viewer_request/qs-redirect.handler
    name: ${self:service}-queries-${opt:stage}

  basicAuth:
    handler: src/viewer_request/basic-auth.handler
    name: ${self:service}-auth-${opt:stage}
    package:
      include:
        - viewer_request/opts.json

  getQkycAuth:
    handler: src/viewer_request/getqkyc-auth.handler
    name: ${self:service}-getqkyc-auth-${opt:stage}
        
  corsViewerResponse:
    handler: src/viewer_response/cors.handler
    name: ${self:service}-cors-${opt:stage}

resources:
  Resources:
    LambdaEdgeRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Statement:
          - Effect: Allow
            Principal:
              Service:
                - edgelambda.amazonaws.com
                - lambda.amazonaws.com
            Action:
            - sts:AssumeRole
        Policies:
          - PolicyName: LambdaEdgeExecutionRole
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: "arn:aws:logs:*:*:*"
