name: Edge Lambdas

on: [push, pull_request]

env:
  AWS_REGION: ${{ secrets.DEFAULT_REGION }}
  AWS_ACCESS_KEY_DEV: ${{ secrets.AWS_ACCESS_KEY_DEV }}
  AWS_SECRET_ACCESS_KEY_DEV: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
  AWS_ACCESS_KEY_PROD: ${{ secrets.AWS_ACCESS_KEY_PROD }}
  AWS_SECRET_ACCESS_KEY_PROD: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
  DEPLOYMENT_BUCKET: ${{ vars.DEPLOYMENT_BUCKET }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set Branch Name
        run: echo "BRANCH_NAME=${{ github.event.pull_request && github.event.pull_request.base.ref || github.ref_name }}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run before script
        run: deploy/setup.sh

      - name: Run deploy script
        run: deploy/deploy.sh

      - name: Deployment finished
        run: echo 'deployed'
